### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ghost** [leque/gauche-mode#7]
How exactly can one install this mode??

**Comment by leque** [comment]
Sorry for late reply.

If you use [package.el](https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html), you would be able to install as follows: checkout this repository, `M-x package-install-file` in emacs, and specify the path to `gauche-mode.el` etc.

I am using [el-get](https://github.com/dimitri/el-get) and [a homegrown recipe](https://github.com/leque/dot.emacs/blob/master/recipes/gauche-mode.rcp) to install this mode, and do not test other installation means well.
